// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"
)

type Querier interface {
	CreateCharge(ctx context.Context, db DBTX, arg CreateChargeParams) error
	CreateChargeProduct(ctx context.Context, db DBTX, arg CreateChargeProductParams) error
	CreateReservation(ctx context.Context, db DBTX, arg CreateReservationParams) error
	CreateReservationProduct(ctx context.Context, db DBTX, arg CreateReservationProductParams) error
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) error
	ExistsChargeByReservationIDAndUserID(ctx context.Context, db DBTX, arg ExistsChargeByReservationIDAndUserIDParams) (bool, error)
	GetCreditCardsByUserId(ctx context.Context, db DBTX, uid string) ([]GetCreditCardsByUserIdRow, error)
	GetPendingReservationByIDAndUserID(ctx context.Context, db DBTX, arg GetPendingReservationByIDAndUserIDParams) ([]GetPendingReservationByIDAndUserIDRow, error)
	GetProductByID(ctx context.Context, db DBTX, productID uint32) (GetProductByIDRow, error)
	GetProductsByIDs(ctx context.Context, db DBTX, productIds []uint32) ([]GetProductsByIDsRow, error)
	GetUserByUid(ctx context.Context, db DBTX, uid string) (GetUserByUidRow, error)
	UpdateReservationStatus(ctx context.Context, db DBTX, arg UpdateReservationStatusParams) error
}

var _ Querier = (*Queries)(nil)
