
-- +migrate Up
CREATE TABLE IF NOT EXISTS `discount_master` (
  `id` INT UNSIGNED PRIMARY KEY COMMENT '割引ID',
  `name` VARCHAR(255) NOT NULL COMMENT '割引キャンペーン名',
  `rate` INT NOT NULL CHECK (`rate` BETWEEN 0 AND 100) COMMENT '割引率（%）',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- +migrate Down
DROP TABLE IF EXISTS `discount_master`;
